name: Altcash frontend app

on:
  push:
    branches:
      - master
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Setup GIT
        run: |
          git config --global user.name "Altcash"
          git config --global user.email "altcash@users.noreply.github.com"
        shell: bash

      - name: GIT tag patch
        if: github.ref == 'refs/heads/master'
        run: yarn version --patch

      - name: GIT tag minor
        if: github.ref == 'refs/heads/production'
        run: yarn version --minor && git push --follow-tags

      - run: git push

      - name: Build steps
        run: |
          yarn install
          yarn build
        shell: bash

      - name: Prepare GIT build
        run: |
          cp -r build heroku_dist
          rm -fr build/
          mkdir build
          mv heroku_dist build/
          cp static.json build/
          cd build
          mv heroku_dist build
        shell: bash

      - name: Deploy frontend app to Heroku
        if: github.ref == 'refs/heads/master'
        run: |
          cd build
          git remote add deployment https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/altcash-staging.git
          git add -f .
          git commit -m "[skip CI]"
          git push -f deployment master:main
        shell: bash

      # - uses: akhileshns/heroku-deploy@v3.11.10
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: 'altcash-staging'
      #     heroku_email: ${{secrets.HEROKU_EMAIL}}
      #     buildpack: 'https://github.com/heroku/heroku-buildpack-static.git'
      #     appdir: 'build'
