name: Altcash frontend app

on:
  push:
    branches:
      - master
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Setup GIT
        run: |
          git config --global user.name "Altcash"
          git config --global user.email "altcash@users.noreply.github.com"
        shell: bash

      - name: GIT tag patch
        if: github.ref == 'refs/heads/master'
        run: yarn version --patch

      - name: GIT tag minor
        if: github.ref == 'refs/heads/production'
        run: yarn version --minor && git push --follow-tags

      # - name: Build steps
      #   run: |
      #     yarn install
      #     yarn build
      #   shell: bash

      - name: Deploy frontend app to Heroku
        if: github.ref == 'refs/heads/master'
        run: |
          git fetch --unshallow origin
          # git remote add deployment https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/altcash-staging.git
          git remote add origin https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/altcash-staging.git
          # git add -f build
          git commit -m "[skip CI]"
          # git push -f deployment master:master
          git push -f origin master
        shell: bash
